Feature: Frontend LLM model selection
    As a user
    I want to choose which LLM model generates a response
    So that I can control whether I use local models or public APIs

    Scenario: Selecting a local LLM model
        Given I am logged into the dashboard
        When I select "Llama" from the model selection menu
        And I send the message "Give me a haiku"
        Then the response should be generated by the Llama model
    
    Scenario: Selecting a public LLM model
        Given I am logged into the dashboard
        When I select "GPT" from the model selection menu
        And I send the message "Give me a haiku"
        Then the response should be generated by the GPT model

    Scenario: Switching between models
        Given I am logged into the dashboard
        When I select "Gemma" from the model selection menu
        And I send the message "Write a two sentence horror story"
        Then the response should be generated by the Gemma model